### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by henryfjordan** [kirsle/github-changelog#2]
Really Noah?

Installing the requirements fails in python3

```
» pip install -r requirements.txt
Collecting pygithub3 (from -r requirements.txt (line 1))
  Using cached pygithub3-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_v/6ydgzcf56g595ls6my7vnch8000_fy/T/pip-build-s7s1g58l/pygithub3/setup.py", line 7, in <module>
        import pygithub3
      File "/private/var/folders/_v/6ydgzcf56g595ls6my7vnch8000_fy/T/pip-build-s7s1g58l/pygithub3/pygithub3/__init__.py", line 10, in <module>
        from github import Github
    ImportError: No module named 'github'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_v/6ydgzcf56g595ls6my7vnch8000_fy/T/pip-build-s7s1g58l/pygithub3/
```

**Comment by kirsle** [comment]
It's an [upstream problem](https://github.com/copitux/python-github3/issues/41) with pygithub3.

Apparently you need to `pip3 install pygithub` first, and then pygithub3 will install. The two dependencies can't co-exist in the same requirements.txt, though, because pip tries to satisfy _all_ dependencies before it attempts to install any of them. `pygithub` has to be fully installed first before `pygithub3` is attempted.

On top of that, the API seems to have changed for the Python 3 version of pygithub3:

```
Traceback (most recent call last):
  File "./gitchangelog.py", line 309, in <module>
    github.main(args)
  File "./gitchangelog.py", line 38, in main
    reset=args.init)
  File "./gitchangelog.py", line 111, in authenticate
    self.api = Github(user=user, token=token, repo=repo)
TypeError: __init__() got an unexpected keyword argument 'token'
```

Send a PR if you wanna fix it. :wink: 

---

Digging into it deeper, the root problem is that pygithub3 uses a relative import which is only supported in Python 2: [from github import Github](https://github.com/copitux/python-github3/blob/master/pygithub3/__init__.py) -- it wants "./github.py" from inside its own package, but Python 3 only uses absolute imports.

Installing `pygithub` first actually masks the problem, because it makes pygithub3 actually import the github.py from an entirely different module and not the local module it expected.

**Comment by kirsle** [comment]
`pygithub3` seems not to be maintained anymore. Somebody opened a pull request to make it work in Python 3 back in 2012 which was never merged. The last commit was in 2014.

We should probably switch to the [PyGithub](https://github.com/PyGithub/PyGithub) module.

**Comment by henryfjordan** [comment]
I looked into a little. Some heavy refactoring will need to happen. I'm not sure when I'll have to chance to play with it

**Comment by henryfjordan** [comment]
```
Traceback (most recent call last):
  File "./gitchangelog.py", line 315, in <module>
    github.main(args)
  File "./gitchangelog.py", line 56, in main
    exclude=args.exclude,
  File "./gitchangelog.py", line 171, in scan_pulls
    pull.number, pull.title, pull.user.get("login")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 69: ordinal not in range(128)
```

Some Jerk used unicode in a PR :angry:
